name: Mirror and run GitLab CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Mirror + trigger CI
      env:
        GITLAB_URL: "https://gitlab.cern.ch/vavolkl/ci-mirror-test"
        GITLAB_HOSTNAME: "gitlab.cern.ch"
        GITLAB_PASSWORD2: ${{ secrets.GITLAB_PASSWORD2 }}
        TESTSECRET3: ${{ secrets.TESTSECRET3 }}
        GITLAB_PROJECT_ID: 94349
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        POLL_TIMEOUT: 25
      run: |
        ls -alh
        git status
        echo ${{ secrets.GITLAB_PASSWORD2 }}
        echo $TESTSECRET3
        #./.github/scripts/gitlabmirror.sh
        #curl -X POST https://api.github.com/repos/vvolkl/ci-mirror-test/dispatches  -H 'Accept: application/vnd.github.everest-preview+json'  -H 'Authorization: token ${GITHUB_TOKEN{'  --data '{"event_type": myevent}'
